apiVersion: v1
kind: Pod
metadata:
  name: nfs-writer-pod
  labels:
    app: nfs-test
spec:
  serviceAccountName: nfs-service-account
  containers:
  - name: writer
    image: registry.redhat.io/ubi8/ubi:latest
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'Data from writer pod at Thu Oct  8 06:39:47 UTC 2026' >> /shared-data/writer.log; sleep 30; done"]
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-data
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-nfsv4-pvc1
  restartPolicy: Always
