apiVersion: v1
kind: Pod
metadata:
  name: nfs-multi-pod
  labels:
    app: nfs-test
spec:
  serviceAccountName: nfs-service-account
  containers:
  - name: multi-access
    image: registry.redhat.io/ubi8/ubi:latest
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'Multi-access pod data at Thu Oct  8 06:40:09 UTC 2026' >> /data2/multi.log; sleep 60; done"]
    volumeMounts:
    - name: shared-volume2
      mountPath: /data2
    securityContext:
      runAsUser: 1003
      runAsGroup: 1003
  volumes:
  - name: shared-volume2
    persistentVolumeClaim:
      claimName: shared-nfsv4-pvc2
  restartPolicy: Always
