apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-nfsv4-pvc1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-cephfs-nfsv4
