apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basic-block-pvc
  namespace: storage-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-ceph-rbd
